spring:
  servlet:
    multipart:
      max-file-size: 50MB # 업로드 가능한 파일의 최대 크기
      max-request-size: 50MB #요청 전체의 최대 크기(여러 파일 포함)
  datasource:
    url: jdbc:mysql://localhost:3306/mini_web02
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        profiles:
          active: local
